// Code generated by MockGen. DO NOT EDIT.
// Source: ./main.go

// Package flusher is a generated GoMock package.
package flusher

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	message "github.com/ozoncp/ocp-chat-api/internal/message"
)

// MockFlusher is a mock of Flusher interface.
type MockFlusher struct {
	ctrl     *gomock.Controller
	recorder *MockFlusherMockRecorder
}

// MockFlusherMockRecorder is the mock recorder for MockFlusher.
type MockFlusherMockRecorder struct {
	mock *MockFlusher
}

// NewMockFlusher creates a new mock instance.
func NewMockFlusher(ctrl *gomock.Controller) *MockFlusher {
	mock := &MockFlusher{ctrl: ctrl}
	mock.recorder = &MockFlusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlusher) EXPECT() *MockFlusherMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockFlusher) Flush(messages []message.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Flush", messages)
}

// Flush indicates an expected call of Flush.
func (mr *MockFlusherMockRecorder) Flush(messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockFlusher)(nil).Flush), messages)
}
